server:
  port: 7011
eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://samlai:samlai123@localhost:7011/eureka/
spring:
  security:
    user:
      name: samlai  # 配置登录的账号是user
      password: samlai123  # 配置登录的密码是password123