server:
  port: 8002
spring:
  application:
    name: hystrix-turbine


eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:7001/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
turbine:
  app-config: feign-hystrix-comsumer-two,feign-hystrix-comsumer
  cluster-name-expression: "'default'"
