server:
  port: 7106
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: feign-hystrix-comsumer-two

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:7001/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true


#设置负载均衡规则:随机访问
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


logging:
  level:
    com.samlai.cloud.feign.CFeignClient: debug

feign:
  hystrix:
    enabled: true
#对一些请求或响应进行压缩
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  client:
    config:
      provider:
        loggerLevel: full

#hystrix配置【断路器】
management:
  endpoints:
    #查看hystrix状态
    health:
      show-details: always
    web:
      exposure:
        include: 'hystrix.stream'




