server:
  port: 9001
spring:
  application:
    name: gateway-zuul


eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:7001/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details:  always

# zuul自定义服务访问路径
zuul:
  routes:
    #feign-comsumer微服务就会被映射到/f/**路径。
    feign-comsumer: /f/**
  #忽略指定微服务
  #使用'*'可忽略所有微服务
  #多个用逗号分隔microservice-provider-user,microservice-consumer-movie
  #ignored-services: '*'
